openapi: 3.0.0
info:
  title: Slack API
  version: 1.0.0
paths:
  /api/chat.postMessage:
    post:
      responses:
        200:
          description: Sends a message to a channel.
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                  - channel
                  - ts
                  - message
                properties:
                  ok:
                    type: boolean
                  channel:
                    type: string
                  ts:
                    type: string
                  message:
                    type: object
  /api/chat.update:
    post:
      responses:
        200:
          description: Updates a message.
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                  - channel
                  - ts
                  - message
                properties:
                  ok:
                    type: boolean
                  channel:
                    type: string
                  ts:
                    type: string
                  message:
                    type: object
  /api/chat.delete:
    post:
      responses:
        200:
          description: Deletes a message.
          content:
            application/json:
              schema:
                type: object
                required:
                  - ok
                  - channel
                  - ts
                properties:
                  ok:
                    type: boolean
                  channel:
                    type: string
                  ts:
                    type: string